# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Interconnection'
copyright = '2022 Ant Group Co., Ltd'
author = 'Secretflow Authors'

# -- Multi-language config ---------------------------------------------------

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

locale_dirs = ['locale/']  # path is example but recommended.
gettext_compact = False  # optional.
gettext_uuid = False  # optional.

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    "sphinx_inline_tabs",
    "sphinx_togglebutton",
    # "myst_parser",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_favicon = '_static/favicon.ico'

html_css_files = [
    'css/custom.css',
]

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"

html_context = {
    "default_mode": "light"
}

html_sidebars = {
    "index": [],
    "**": ["search-field", "sidebar-nav-bs"]
}

html_theme_options = {
    "logo": {
        "text": "Interconnection",
        "image_light": "logo.png",
        "image_dark": "logo-dark.png",
    },
    "pygment_light_style": "tango",
    "pygment_dark_style": "native",
    "external_links": [
        {"name": "SecretFlow", "url": "https://secretflow.readthedocs.io/"},
    ],
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/secretflow/interconnection",
            "icon": "fa-brands fa-github",
            "type": "fontawesome",
        },
    ],
    "footer_items": ["copyright"],
    "secondary_sidebar_items": ["page-toc"],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
